# Config data exposed by config server
info:
  foo: bong
  someList: [2, 3, 7]

cis:
  rest:
    uri: http://localhost:12345
    
enableConsoleAppender: false
application-name: Swisscom Text To Speech Gateway
log4j-default-level: info
request:
  template-path: TTS_request_template
  staging-path: .
  staging-file-prefix: Athene_PRD_
sftp:
  known-hosts-file: ~/.ssh/known_hosts
  private-key-file: ~/.ssh/id_rsa
  host:
  use-password: false
  user: FTP-USER
  password:
  port: 22
  remote-path: .
  delete-file-after-transfer: true
